name: test octokit request action
on:
  workflow_dispatch:

jobs:
  check-project-existence:
    runs-on: ubuntu-latest
    env:
      repository: "${{github.repository}}"
      project-name: "Request Action Validation"
    outputs:
      project-exists: ${{ steps.check_project_exists.outpu.project_exists }}
    steps:
      - name: retrieve repository project list
        uses: octokit/request-action@v2.1.6
        id: get_repository_projects
        with:
          route: GET /repos/{repo}/projects
          repo: ${{env.repository}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: check if project already exists
        id: check_project_exists
        run: |
               project=$(echo '${{ steps.get_repository_projects.outputs.data }}' | jq '.[] | select(.name=="${{env.project-name}}" and .state=="open")')
               echo "::set-output name=project_exists::$( [ ${#project} = 0 ]; echo $?)"

#      - name: status
#        run: echo '${{ steps.get_repository_projects.outputs.status }}'
#        
  create-project:
    needs: check-project-existence
    if: ${{needs.check-project-existence.outputs.project-exists}}==0
    runs-on: ubuntu-latest
    env:
      repository: "${{github.repository}}"
      project-name: "Request Action Validation"
    steps:
      - name: exists
        run: echo '${{ needs.check-project-existence.outputs.project-exists }}'
               
#      - uses: octokit/request-action@v2.1.6
#        id: get_latest_release
#        with:
#          route: POST /repos/{owner}/{repo}/projects
#          owner: belcebus
#          repo: issuecomment-test
#          name: 'Projects Documentation'
#          body: 'Developer documentation project for the developer site.'
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
#      - run: echo '${{ steps.get_latest_release.outputs.data }}'
