name: test octokit request action
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: octokit/request-action@v2.1.6
        id: get_latest_release
        with:
          route: POST /repos/{owner}/{repo}/projects
          owner: belcebus
          repo: issuecomment-test
          name: 'Projects Documentation'
          body: 'Developer documentation project for the developer site.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - run: echo '${{ steps.get_latest_release.outputs.data }}'
