name: test octokit request action
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: octokit/request-action@master
        id: get_latest_release
        with:
          route: GET /repos/{param1}/{param2}/releases/latest
          param1: belcebus
          param2: issuecomment-test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      

