name: issue testing

on:
  issues:
    types:
      - opened
      - reopened
      - edited
  workflow_dispatch:
    

jobs:
  get-info:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue }}
    steps:
      - name: print issue body
        run: |
          echo "${{ github.event.issue.body }}"
          echo "${{ github.event.issue }}"
          
