name: Create security validation project board
on:
  workflow_dispatch:

env:
  PROJECT-NAME: "Request Action Validation"
  REPOSITORY: "${{github.repository}}"

jobs:
  check-project:
    name: Create repository project
    runs-on: ubuntu-latest
    steps:

      - name: retrieve repository project list
        id: get-repository-projects
        uses: octokit/request-action@v2.1.6
        with:
          route: GET /repos/{repo}/projects
          repo: ${{ env.REPOSITORY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: check if project already exists
        id: check-project-exists
        run: |
              project=$(echo '${{ steps.get-repository-projects.outputs.data }}' | jq '.[] | select(.name=="${{ env.PROJECT-NAME }}" and .state=="open")')
              if [ ${ #project } != 0 ];
              then
                echo "::set-output name=project-exists::1"
                echo "::error title='Project already exists'::'A project named ${{ env.PROJECT-NAME }} already exists'"
                return 1
              fi

      - name: show result
        run: echo "${{steps.check-project-exists.outputs.project-exists}}"
    
      - name: create the repositoy project
        id: create-project
        uses: octokit/request-action@v2.1.6
        with:
          route: POST /repos/{repo}/projects
          repo: ${{ env.REPOSITORY }}
          name: ${{ env.PROJECT-NAME }}
          body: "Automatic created. Project for thir party validation process requests"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: return repository project id
        id: get-project-id
        run: |
              project_id=$(echo '${{ steps.create-project.outputs.data }}' | jq -e '.id')
              echo ::set-output name=project-id::${ project_id }
              echo ${ project_id }
 
      - name: create columns
        run: echo ${{ steps.get-project-id.outputs.project-id }}